### PR TITLE
add fetch logs functionality in e2e dashboard UI

### PR DESCRIPTION
**Pull request by Aman-Codes**
## Proposed changes

This PR adds fetch logs functionality in e2e dashboard UI. 

## Issue
Closes litmuschaos/litmus#3112

## Dependency
This PR contains commit of #333 and adds fetch log functionality on top of that.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus-e2e/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] I have added necessary documentation (if appropriate)
- [x] I have added Screenshots or Terminal snippets in the PR comment to validate the successful execution of changes

## Screenshots:

image
image
image

### CODE REVIEW

**Comment by Aman-Codes** [comment]
Deployed it at https://aman-codes.github.io/litmus-e2e/dashboard

**Comment by uditgaurav** [comment]
Awesome Thanks @Aman-Codes!

**Comment by Jonsy13** [comment]
On clicking on commit ids in Portal pipeline, it is taking to litmusgo PTAL

**Comment by Jonsy13** [comment]
First 2 pipeline runs are having a different color, any reason?
Screenshot from 2021-11-22 20-51-43

**Comment by Jonsy13** [comment]
Should we increase size of circle a little bit ? @uditgaurav @Aman-Codes 
Screenshot from 2021-11-22 20-53-43

**Comment by Jonsy13** [comment]
There is a time limit, after which the logs & artifacts are removed by github. So, they won't be available after 7 days or 1 month. Looks like we haven't handled the case of unavailability of artifacts or logs. Checked on 6 months old pipeline. - cc: @uditgaurav 

Screenshot from 2021-11-22 20-56-21

**Comment by Aman-Codes** [comment]
Hi @Jonsy13 fixed all the given suggestions and redeployed to https://aman-codes.github.io/litmus-e2e/dashboard/

**Review by Jonsy13 — APPROVED** [review]

**Comment by Aman-Codes** [comment]
@uditgaurav @Jonsy13 
Fixed the GitHub commit link for litmus repo

**Review by uditgaurav — APPROVED** [review]

**Pull request merged**
