### PR TITLE
(bug): Fix adding wait time for chaosengine verdict

### PR DESCRIPTION
**Pull request by uditgaurav**
- Fix adding wait time for chaosengine verdict
Signed-off-by: Udit Gaurav <uditgaurav@gmail.com>

### CODE REVIEW

**Comment by ksatchit** [comment]
cc: @rahulchheda -- we seem to be hitting this often - Awaited status on a passed test. What is your assessment?

**Comment by rahulchheda** [comment]
@ksatchit , I tried to debug this issue with @uditgaurav. But it's really inconsistent (behavior), just to make sure that everything is happening correctly just added the more timeout. If this was a re-occurring issue for all experiments then their might be a code error, but this is really inconsistent, thatw hy trying to solve by timeout

**Comment by rahulchheda** [comment]
@uditgaurav Seems like openebs experiment pipelines are failing, but the timeout seems to be added just for generic ones.

**Comment by rahulchheda** [comment]
Ohh great! You did it in separate PR. Thanks @uditgaurav

**Comment by ksatchit** [comment]
@rahulchheda do we need to increase timeout in runner as well?

**Comment by rahulchheda** [comment]
Lets try this first, if this doesn't work, i will fix it form runner side.

**Pull request merged**
